use std::collections::HashMap;
use std::fs;

use tempfile::TempDir;

use envtools_application::port::StateFileWriter;
use envtools_domain::service::group_policy::ResolvedEnvironment;
use envtools_infrastructure::FileStateWriter;

fn make_resolved(vars: Vec<(&str, &str)>) -> ResolvedEnvironment {
    let variables: HashMap<String, String> = vars
        .iter()
        .map(|(k, v)| (k.to_string(), v.to_string()))
        .collect();
    let managed_keys = variables.keys().cloned().collect();
    ResolvedEnvironment {
        variables,
        managed_keys,
    }
}

#[test]
fn write_bash_creates_sourceable_file() {
    let dir = TempDir::new().unwrap();
    let writer = FileStateWriter::new(dir.path());
    let resolved = make_resolved(vec![("JAVA_HOME", "/usr/lib/jvm"), ("GO_PATH", "/go")]);

    writer.write_bash(&resolved).unwrap();

    let content = fs::read_to_string(dir.path().join("active.env")).unwrap();
    assert!(content.contains("export JAVA_HOME=\"/usr/lib/jvm\""));
    assert!(content.contains("export GO_PATH=\"/go\""));
    assert!(content.contains("__ENVTOOLS_MANAGED_KEYS="));
    assert!(content.starts_with("# Generated by envtools"));
}

#[test]
fn write_powershell_creates_ps1_file() {
    let dir = TempDir::new().unwrap();
    let writer = FileStateWriter::new(dir.path());
    let resolved = make_resolved(vec![("JAVA_HOME", "C:\\Java")]);

    writer.write_powershell(&resolved).unwrap();

    let content = fs::read_to_string(dir.path().join("active.ps1")).unwrap();
    assert!(content.contains("$env:JAVA_HOME = \"C:\\Java\""));
    assert!(content.contains("$env:__ENVTOOLS_MANAGED_KEYS"));
}

#[test]
fn write_fish_creates_fish_file() {
    let dir = TempDir::new().unwrap();
    let writer = FileStateWriter::new(dir.path());
    let resolved = make_resolved(vec![("MY_VAR", "hello")]);

    writer.write_fish(&resolved).unwrap();

    let content = fs::read_to_string(dir.path().join("active.fish")).unwrap();
    assert!(content.contains("set -gx MY_VAR \"hello\""));
    assert!(content.contains("set -gx __ENVTOOLS_MANAGED_KEYS"));
}

#[test]
fn write_empty_environment() {
    let dir = TempDir::new().unwrap();
    let writer = FileStateWriter::new(dir.path());
    let resolved = make_resolved(vec![]);

    writer.write_bash(&resolved).unwrap();

    let content = fs::read_to_string(dir.path().join("active.env")).unwrap();
    assert!(content.contains("# Generated by envtools"));
    assert!(content.contains("__ENVTOOLS_MANAGED_KEYS=\"\""));
}
