use std::fs;
use std::path::PathBuf;

use envtools_application::port::StateFileWriter;
use envtools_domain::error::DomainError;
use envtools_domain::service::group_policy::ResolvedEnvironment;

const MANAGED_KEYS_REG: &str = "__ENVTOOLS_MANAGED_KEYS";

pub struct FileStateWriter {
    base_dir: PathBuf,
}

impl FileStateWriter {
    pub fn new(base_dir: impl Into<PathBuf>) -> Self {
        Self {
            base_dir: base_dir.into(),
        }
    }

    fn ensure_dir(&self) -> Result<(), DomainError> {
        fs::create_dir_all(&self.base_dir)
            .map_err(|e| DomainError::GroupNotFound(format!("failed to create state dir: {e}")))
    }

    fn write_file(&self, filename: &str, content: &str) -> Result<(), DomainError> {
        self.ensure_dir()?;
        let path = self.base_dir.join(filename);
        fs::write(&path, content)
            .map_err(|e| DomainError::GroupNotFound(format!("failed to write {filename}: {e}")))
    }
}

impl StateFileWriter for FileStateWriter {
    fn write_bash(&self, resolved: &ResolvedEnvironment) -> Result<(), DomainError> {
        let mut lines = Vec::new();
        lines.push("# Generated by envtools - DO NOT EDIT".to_string());
        lines.push(format!(
            "# timestamp: {}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs()
        ));
        lines.push(String::new());

        // Export managed keys list for unset tracking
        let keys_list = resolved.managed_keys.join(" ");
        lines.push(format!("__ENVTOOLS_MANAGED_KEYS=\"{keys_list}\""));
        lines.push(String::new());

        let mut sorted_vars: Vec<_> = resolved.variables.iter().collect();
        sorted_vars.sort_by_key(|(k, _)| k.as_str());

        for (key, value) in &sorted_vars {
            lines.push(format!("export {key}=\"{value}\""));
        }

        self.write_file("active.env", &lines.join("\n"))
    }

    fn write_powershell(&self, resolved: &ResolvedEnvironment) -> Result<(), DomainError> {
        let mut lines = Vec::new();
        lines.push("# Generated by envtools - DO NOT EDIT".to_string());
        lines.push(String::new());

        let keys_list = resolved.managed_keys.join(",");
        lines.push(format!("$env:__ENVTOOLS_MANAGED_KEYS = \"{keys_list}\""));
        lines.push(String::new());

        let mut sorted_vars: Vec<_> = resolved.variables.iter().collect();
        sorted_vars.sort_by_key(|(k, _)| k.as_str());

        for (key, value) in &sorted_vars {
            lines.push(format!("$env:{key} = \"{value}\""));
        }

        self.write_file("active.ps1", &lines.join("\r\n"))
    }

    fn write_fish(&self, resolved: &ResolvedEnvironment) -> Result<(), DomainError> {
        let mut lines = Vec::new();
        lines.push("# Generated by envtools - DO NOT EDIT".to_string());
        lines.push(String::new());

        let keys_list = resolved.managed_keys.join(" ");
        lines.push(format!("set -gx __ENVTOOLS_MANAGED_KEYS {keys_list}"));
        lines.push(String::new());

        let mut sorted_vars: Vec<_> = resolved.variables.iter().collect();
        sorted_vars.sort_by_key(|(k, _)| k.as_str());

        for (key, value) in &sorted_vars {
            lines.push(format!("set -gx {key} \"{value}\""));
        }

        self.write_file("active.fish", &lines.join("\n"))
    }

    #[cfg(windows)]
    fn write_system_env(&self, resolved: &ResolvedEnvironment) -> Result<(), DomainError> {
        use winreg::enums::*;
        use winreg::RegKey;

        let hkcu = RegKey::predef(HKEY_CURRENT_USER);
        let (env_key, _) = hkcu
            .create_subkey("Environment")
            .map_err(|e| DomainError::GroupNotFound(format!("registry open failed: {e}")))?;

        // Read previously managed keys and remove them
        if let Ok(old_keys) = env_key.get_value::<String, _>(MANAGED_KEYS_REG) {
            for key in old_keys.split(',').filter(|k| !k.is_empty()) {
                let _ = env_key.delete_value(key);
            }
        }

        if resolved.managed_keys.is_empty() {
            let _ = env_key.delete_value(MANAGED_KEYS_REG);
        } else {
            // Write new managed keys tracker
            let keys_csv = resolved.managed_keys.join(",");
            env_key
                .set_value(MANAGED_KEYS_REG, &keys_csv)
                .map_err(|e| DomainError::GroupNotFound(format!("registry write failed: {e}")))?;

            // Write each variable
            for (key, value) in &resolved.variables {
                env_key.set_value(key.as_str(), value).map_err(|e| {
                    DomainError::GroupNotFound(format!("registry set {key} failed: {e}"))
                })?;
            }
        }

        // Broadcast WM_SETTINGCHANGE so new processes pick up the changes
        broadcast_env_change();

        Ok(())
    }
}

#[cfg(windows)]
fn broadcast_env_change() {
    std::thread::spawn(|| {
        use windows::core::*;
        use windows::Win32::Foundation::*;
        use windows::Win32::UI::WindowsAndMessaging::*;

        unsafe {
            let _ = SendMessageTimeoutW(
                HWND_BROADCAST,
                WM_SETTINGCHANGE,
                WPARAM(0),
                LPARAM(w!("Environment").as_ptr() as isize),
                SMTO_ABORTIFHUNG,
                2000,
                None,
            );
        }
    });
}
