use std::fs;
use std::path::PathBuf;

use envtools_domain::error::DomainError;
use envtools_domain::service::group_policy::ResolvedEnvironment;
use envtools_application::port::StateFileWriter;

pub struct FileStateWriter {
    base_dir: PathBuf,
}

impl FileStateWriter {
    pub fn new(base_dir: impl Into<PathBuf>) -> Self {
        Self {
            base_dir: base_dir.into(),
        }
    }

    fn ensure_dir(&self) -> Result<(), DomainError> {
        fs::create_dir_all(&self.base_dir)
            .map_err(|e| DomainError::GroupNotFound(format!("failed to create state dir: {e}")))
    }

    fn write_file(&self, filename: &str, content: &str) -> Result<(), DomainError> {
        self.ensure_dir()?;
        let path = self.base_dir.join(filename);
        fs::write(&path, content)
            .map_err(|e| DomainError::GroupNotFound(format!("failed to write {filename}: {e}")))
    }
}

impl StateFileWriter for FileStateWriter {
    fn write_bash(&self, resolved: &ResolvedEnvironment) -> Result<(), DomainError> {
        let mut lines = Vec::new();
        lines.push("# Generated by envtools - DO NOT EDIT".to_string());
        lines.push(format!(
            "# timestamp: {}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs()
        ));
        lines.push(String::new());

        // Export managed keys list for unset tracking
        let keys_list = resolved.managed_keys.join(" ");
        lines.push(format!("__ENVTOOLS_MANAGED_KEYS=\"{keys_list}\""));
        lines.push(String::new());

        let mut sorted_vars: Vec<_> = resolved.variables.iter().collect();
        sorted_vars.sort_by_key(|(k, _)| k.as_str());

        for (key, value) in &sorted_vars {
            lines.push(format!("export {key}=\"{value}\""));
        }

        self.write_file("active.env", &lines.join("\n"))
    }

    fn write_powershell(&self, resolved: &ResolvedEnvironment) -> Result<(), DomainError> {
        let mut lines = Vec::new();
        lines.push("# Generated by envtools - DO NOT EDIT".to_string());
        lines.push(String::new());

        let keys_list = resolved.managed_keys.join(",");
        lines.push(format!(
            "$env:__ENVTOOLS_MANAGED_KEYS = \"{keys_list}\""
        ));
        lines.push(String::new());

        let mut sorted_vars: Vec<_> = resolved.variables.iter().collect();
        sorted_vars.sort_by_key(|(k, _)| k.as_str());

        for (key, value) in &sorted_vars {
            lines.push(format!("$env:{key} = \"{value}\""));
        }

        self.write_file("active.ps1", &lines.join("\r\n"))
    }

    fn write_fish(&self, resolved: &ResolvedEnvironment) -> Result<(), DomainError> {
        let mut lines = Vec::new();
        lines.push("# Generated by envtools - DO NOT EDIT".to_string());
        lines.push(String::new());

        let keys_list = resolved.managed_keys.join(" ");
        lines.push(format!("set -gx __ENVTOOLS_MANAGED_KEYS {keys_list}"));
        lines.push(String::new());

        let mut sorted_vars: Vec<_> = resolved.variables.iter().collect();
        sorted_vars.sort_by_key(|(k, _)| k.as_str());

        for (key, value) in &sorted_vars {
            lines.push(format!("set -gx {key} \"{value}\""));
        }

        self.write_file("active.fish", &lines.join("\n"))
    }
}
